"""update database 13/09/2023

Revision ID: 339cf2f9046b
Revises: 57668de1c69c
Create Date: 2023-09-13 21:22:13.541313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339cf2f9046b'
down_revision: Union[str, None] = '57668de1c69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yre_article_element', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('yre_sentence', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yre_sentence', 'index')
    op.drop_column('yre_article_element', 'index')
    # ### end Alembic commands ###
