"""update database 13/09/2023-2

Revision ID: 3ce41e3c8169
Revises: 339cf2f9046b
Create Date: 2023-09-13 21:24:32.750065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce41e3c8169'
down_revision: Union[str, None] = '339cf2f9046b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yre_sentence_token', 'word_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yre_sentence_token', 'word_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
