"""add Translation

Revision ID: 488068894ff7
Revises: 52e5e6f8d600
Create Date: 2023-09-13 10:31:16.780806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488068894ff7'
down_revision: Union[str, None] = '52e5e6f8d600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yre_translation',
    sa.Column('from_word_id', sa.Uuid(), nullable=False),
    sa.Column('to_word_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_word_id'], ['yre_word.id'], ),
    sa.ForeignKeyConstraint(['to_word_id'], ['yre_word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yre_translation')
    # ### end Alembic commands ###
