"""create basedata

Revision ID: 7ddf550fb781
Revises: 
Create Date: 2023-09-13 17:20:58.973310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddf550fb781'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yre_article',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_content', sa.String(), nullable=False),
    sa.Column('source_link', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yre_language_reference',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('yre_part_Of_speech_reference',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('yre_article_element',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['yre_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yre_word',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('example_use', sa.String(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('part_of_speech_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['yre_language_reference.id'], ),
    sa.ForeignKeyConstraint(['part_of_speech_id'], ['yre_part_Of_speech_reference.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('yre_sentence',
    sa.Column('article_element_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_element_id'], ['yre_article_element.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yre_translation',
    sa.Column('from_word_id', sa.Uuid(), nullable=False),
    sa.Column('to_word_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_word_id'], ['yre_word.id'], ),
    sa.ForeignKeyConstraint(['to_word_id'], ['yre_word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yre_sentence_token',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('sentence_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['yre_sentence.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['yre_word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yre_sentence_token')
    op.drop_table('yre_translation')
    op.drop_table('yre_sentence')
    op.drop_table('yre_word')
    op.drop_table('yre_article_element')
    op.drop_table('yre_part_Of_speech_reference')
    op.drop_table('yre_language_reference')
    op.drop_table('yre_article')
    # ### end Alembic commands ###
